### ISSUE TITLE
API: new method with order info

### ISSUE THREAD

**Issue by susuper** [thodex-exchange/thodex-php-api#1]
Hello.
I would like to ask developers to implement new API method which exists at majority of exchanges - "Order info".
It is very convenient to get order information (status, filled quantity, etc) by its ID. At the moment Thodex exchange offers only "Order history" method, which is costly for exchange in case of big amount of user's orders.
Thank you!

**Comment by letreset** [comment]
Hi,
Thanks for your suggestion. We will implement this feature and inform you.

**Comment by ersisk** [comment]
Order info method added. Here you go:
https://api.thodex.com/#api-Market-getFinishedOrder
https://api.thodex.com/#api-Market-getFinishedOrderInfo
https://api.thodex.com/#api-Market-getOpenOrderInfo
