### ISSUE TITLE
Ticker

### ISSUE THREAD

**Issue by samemen** [thodex-exchange/thodex-php-api#3]
http://ticker.thodex.com/ Ticker verileri çok gec güncelleniyor bi el atsanız bunada güzel olucak. 1 dk felan sürüyor rakamların güncellenmesi!.

**Comment by letreset** [comment]
Merhaba,
ticker datası dakikada bir güncellenmektedir. 
https://api.thodex.com/#api-Public-getMarketStatus
rpc isteğinden ya da websocket üzerinden gerçek zamanlı verileri alabilirsiniz.
https://api.thodex.com/#api-_footer

**Comment by samemen** [comment]
Websocket yavaş kalıyor tüm verileri almada public api'de her market icin GET atacagım için gereksiz işlem oluyor tek sayfada tüm fiyatlara ulaşmak mantıklı olan süreyi azaltmanız mümkünse düşürseniz hesaplamarı hızlı şekilde yaparım.
